Kiểm tra dữ liệu sử dụng các mô hình Gradient Boosting

In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

Đọc data từ dữ liệu nhà nghỉ đã crawl

In [2]:
data = pd.read_csv("../Merge/final_selected_data.csv")
data.head()

,room_type_id,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,...,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng,hotel_id,room_room_type_name,hotel_name,hotel_address,region
0,1,1,0,0,0,0,0,0,0,0,...,1,0,1,0,0,71897952,Phòng Deluxe Có Giường Cỡ King (Deluxe King Room),Nha Nghi Nhung - Nhung Motel,"73 Đoàn Thị Điểm, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
1,2,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng Tiêu Chuẩn (Standard Room),Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
2,3,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng gia đình có ban công (Family Room with B...,Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
3,4,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,65481766,Phòng Có Giường Cỡ King Với Ban Công (King Roo...,Baly Hotel Bà Rịa City (Baly Hotel Ba Ria City),"QL51, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
4,5,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,5808626,Phòng Studio Executive (Studio Executive),Citadines Central Bình Dương (Citadines Centra...,"Số 328C, Đại lộ B nh Dương, Khu phố Hưng Lộc, ...",Bình Dương

Tạo một DataFrame mới tên là data2 từ data, ta bỏ 5 trường thuộc tính là hotel_id, hotel_name, room_room_type_name, hotel_name và hotel_address, views và regions

In [3]:
data2 = data.drop(columns=[
    'hotel_id',
    'hotel_name',
    'room_room_type_name',
    'hotel_address',
    'room_type_id', 
    'views', 'region'
])
data2.head()

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,price_option_price,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,289522.0,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,361111.0,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,601852.0,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,425926.0,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,1450000.0,2,0,0,0,1,0,0,0,0

Khi kiểm tra giá trị các trường ta nhận thấy trường sqm và price có biên độ giá trị khá cao, dễ ảnh hưởng đến kết quả khi train mô hình, ta cần chuẩn hoá về phân phối chuẩn (mean=0, variance =1)

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data2['sqm'] = scaler.fit_transform(data2[['sqm']])
data2['price_option_price'] = scaler.fit_transform(data2[['price_option_price']])

In [5]:
print(data2['sqm'].mean())      # ≈ 0
print(data2['sqm'].var())

3.305948255447458e-17
1.0000553924555475

Lưu kết quả của data đã tiền xử lý (optional)

In [6]:
#data2.to_csv('preprocess_final_totrain_rforest.csv')
#data2.head()

Xử lý trường hợp NaN của price_option_price

In [7]:
data2['price_option_price'] = data2['price_option_price'].fillna(data2['price_option_price'].median())
data2['sqm'] = data2['sqm'].fillna(data2['sqm'].median())

In [8]:
x_data = data2.drop(columns=['price_option_price'])
y_data = data2['price_option_price']
x_data

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,bedroom_count,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,0,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,0,2,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19515,0,0,1,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
19516,0,0,1,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
19517,0,0,0,0,1,0,0,0,0,2,...,0,4,0,1,0,1,0,1,0,0
19518,1,0,0,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
19519,1,0,0,0,0,0,0,0,0,1,...,0,4,0,1,0,1,0,1,0,0

In [9]:
y_data

0       -0.216136
1       -0.204025
2       -0.163296
3       -0.193059
4       -0.019804
           ...
19515   -0.227807
19516   -0.219289
19517   -0.218832
19518   -0.230825
19519   -0.217107
Name: price_option_price, Length: 19520, dtype: float64

Tách dữ liệu x,y ra thành 2 phần là x_train, y_train và x_test, y_test

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.25, random_state=42)

In [11]:
X_train.shape

(14640, 43)

In [12]:
X_test.shape

(4880, 43)

Tạo mô hình HistGradientBoostingRegressor để huấn luyện với tập luyện

In [13]:
hist_gboost = HistGradientBoostingRegressor(loss='squared_error', learning_rate=0.08, max_iter=1600).fit(X_train, y_train)

Đo lường điểm R2, MAE, MSE của mô hình

In [14]:
#R2 score
hist_gboost.score(X_test, y_test)

0.11158993335373768

In [15]:

y_pred = hist_gboost.predict(X_test)
mean_squared_error(y_test, y_pred)
#MSE score

0.6165894200098881

In [16]:
#MAE score
mean_absolute_error(y_test, y_pred)

0.16140353912106797

Tạo mô hình AdaBoostRegressor

In [17]:
from sklearn.ensemble import AdaBoostRegressor
ada_gboost = AdaBoostRegressor(n_estimators = 180, learning_rate = 0.04, loss= 'linear')
ada_gboost.fit(X_train, y_train)

AdaBoostRegressor(learning_rate=0.04, n_estimators=180)

In [18]:
y_pred_ada = ada_gboost.predict(X_test)
print(mean_squared_error(y_test, y_pred_ada)) #MSE
print(mean_absolute_error(y_test, y_pred_ada)) #MAE
print(ada_gboost.score(X_test, y_test)) #R2

1.6254141043575006
0.21631793025537624
-1.3419705332551182

Tạo mô hình Decision Tree để đánh giá data

In [19]:
from sklearn.tree import DecisionTreeRegressor
decision_tree = DecisionTreeRegressor(criterion = 'squared_error', splitter='random')
decision_tree.fit(X_train, y_train)

DecisionTreeRegressor(splitter='random')

In [20]:
y_pred_decisiontree = decision_tree.predict(X_test)
print(decision_tree.score(X_test, y_test)) #R2 score 
print(mean_absolute_error(y_test,y_pred_decisiontree)) #MAR
print(mean_squared_error(y_test, y_pred_decisiontree))#MSE

0.007857075047858708
0.14252862952304998
0.6885838574212519

Tạo mô hình Linear Regression để đánh giá data

In [21]:
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression(n_jobs = -1).fit(X_train, y_train)
y_pred_linearregression = linear_regression.predict(X_test)
print(linear_regression.score(X_test, y_test)) #R2 score 
print(mean_absolute_error(y_test,y_pred_linearregression)) #MAR
print(mean_squared_error(y_test, y_pred_linearregression))#MSE

0.08731030448514177
0.2071616083987533
0.6334403797684337