Kiểm tra dữ liệu sử dụng các mô hình Gradient Boosting

In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler

Đọc data từ dữ liệu nhà nghỉ đã crawl

In [2]:
data = pd.read_csv("../Merge/final_selected_data.csv")
data.head()

,room_type_id,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,...,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng,hotel_id,room_room_type_name,hotel_name,hotel_address,region
0,1,1,0,0,0,0,0,0,0,0,...,1,0,1,0,0,71897952,Phòng Deluxe Có Giường Cỡ King (Deluxe King Room),Nha Nghi Nhung - Nhung Motel,"73 Đoàn Thị Điểm, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
1,2,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng Tiêu Chuẩn (Standard Room),Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
2,3,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng gia đình có ban công (Family Room with B...,Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
3,4,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,65481766,Phòng Có Giường Cỡ King Với Ban Công (King Roo...,Baly Hotel Bà Rịa City (Baly Hotel Ba Ria City),"QL51, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
4,5,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,5808626,Phòng Studio Executive (Studio Executive),Citadines Central Bình Dương (Citadines Centra...,"Số 328C, Đại lộ B nh Dương, Khu phố Hưng Lộc, ...",Bình Dương

Tạo một DataFrame mới tên là data2 từ data, ta bỏ 5 trường thuộc tính là hotel_id, hotel_name, room_room_type_name, hotel_name và hotel_address, views và regions

In [3]:
data2 = data.drop(columns=[
    'hotel_id',
    'hotel_name',
    'room_room_type_name',
    'hotel_address',
    'room_type_id', 
    'views', 'region'
])
data2.head()

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,price_option_price,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,289522.0,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,361111.0,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,601852.0,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,425926.0,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,1450000.0,2,0,0,0,1,0,0,0,0

In [4]:
for col in data2.columns:
    print(f"{col}:")
    print(data2[col].unique())
    print("-" * 40)

large_double_bed:
[1 0]
----------------------------------------
large_bed:
[0 1]
----------------------------------------
single_bed:
[0 1]
----------------------------------------
sofa_bed:
[0 1]
----------------------------------------
double_bed:
[0 1]
----------------------------------------
small_double_bed:
[0 1]
----------------------------------------
king_size_bed:
[0 1]
----------------------------------------
futon_mattress:
[0 1]
----------------------------------------
bunk_bed:
[0 1]
----------------------------------------
flexibility_score:
[1 2 3 5]
----------------------------------------
sqm:
[1.800e+01 3.000e+01 4.500e+01 2.000e+01 3.500e+01 5.000e+01 5.400e+01
 6.000e+01 6.300e+01 7.100e+01 2.100e+01 3.200e+01 2.500e+01 4.000e+01
 2.200e+01 1.200e+01 2.600e+01 3.800e+01       nan 3.300e+01 4.300e+01
 7.000e+01 5.200e+01 6.200e+01 7.800e+01 3.400e+01 1.700e+01 4.100e+01
 2.800e+01 7.500e+01 6.600e+01 1.000e+01 2.400e+01 1.600e+01 5.800e+01
 1.500e+01 5.500e+01 6.500e+01 8.000e+01 2.300e+01 7.600e+01 8.500e+01
 6.800e+01 4.200e+01 7.200e+01 5.600e+01 2.700e+01 1.000e+02 4.900e+01
 5.100e+01 9.600e+01 3.100e+01 4.800e+01 1.100e+02 4.700e+01 1.090e+02
 4.600e+01 9.200e+01 1.250e+02 4.400e+01 3.700e+01 5.900e+01 1.080e+02
 3.600e+01 1.900e+01 2.180e+02 1.060e+02 8.200e+01 1.000e+03 8.800e+01
 2.000e+02 6.900e+01 6.400e+01 9.500e+01 5.000e+02 7.400e+01 6.700e+01
 1.200e+02 6.200e+02 2.400e+02 2.040e+02 1.100e+01 1.400e+01 1.300e+02
 7.900e+01 1.600e+02 2.500e+02 9.000e+01 1.500e+02 9.000e+00 2.100e+02
 1.980e+02 1.680e+02 1.300e+01 4.000e+02 1.120e+02 2.900e+01 1.300e+03
 3.500e+02 3.900e+01 9.800e+01 1.230e+02 1.340e+02 8.300e+01 6.100e+01
 9.300e+01 5.300e+01 7.700e+01 1.030e+02 1.050e+02 1.350e+02 1.700e+02
 2.770e+02 1.800e+02 2.250e+02 8.700e+01 1.180e+02 1.790e+02 1.970e+02
 2.000e+03 3.000e+03 6.000e+03 1.020e+02 1.110e+02 5.700e+01 1.540e+02
 3.000e+02 1.380e+02 9.400e+01 7.300e+01 1.750e+02 2.650e+02 1.410e+02
 1.070e+02 2.690e+02 8.400e+01 1.150e+02 8.600e+01 1.170e+02 1.720e+02
 8.900e+01 1.140e+02 1.330e+02 1.640e+02 9.700e+01 3.000e+00 4.200e+02
 1.400e+02 9.900e+01 1.950e+02 1.010e+02 1.390e+02 1.820e+02 1.160e+02
 2.030e+02 2.550e+02 8.100e+01 2.470e+02 1.210e+02 6.800e+02 5.500e+02
 1.590e+02 5.360e+02 1.040e+02 3.200e+02 1.220e+02 1.650e+02 2.120e+02
 2.700e+02 2.200e+02 2.750e+02 1.310e+02 2.370e+02 2.600e+02 3.650e+02
 1.960e+02 6.000e+02 2.900e+02 4.500e+02 3.900e+02 3.150e+02 7.000e+02
 4.800e+02 1.130e+02 1.100e+03 4.000e+03 4.400e+02 3.700e+02 3.800e+02
 2.800e+02 8.000e+02 1.840e+02 7.000e+00 1.240e+02 1.291e+03 1.200e+03
 4.000e+00 5.000e+00 1.890e+02 3.600e+02 6.000e+00]
----------------------------------------
bathroom_count:
[ 1  0  2  3 12  5 10  7 13  8 15  4  6  9 11 16 14 21 20 18]
----------------------------------------
is_private_bathroom:
[1 0]
----------------------------------------
balcony-terrace:
[1 0]
----------------------------------------
closet:
[0 1]
----------------------------------------
air_conditioning:
[1 0]
----------------------------------------
hair_dryer:
[0 1]
----------------------------------------
complimentary-bottled-water:
[0 1]
----------------------------------------
bathtub:
[0 1]
----------------------------------------
shower:
[0 1]
----------------------------------------
refrigerator:
[0 1]
----------------------------------------
high-floor:
[0 1]
----------------------------------------
dressing-room:
[0 1]
----------------------------------------
ground-floor:
[0 1]
----------------------------------------
private-pool:
[0 1]
----------------------------------------
top-floor:
[0 1]
----------------------------------------
complimentary-instant-coffee:
[0 1]
----------------------------------------
electric-blanket:
[0 1]
----------------------------------------
free-welcome-drink:
[0 1]
----------------------------------------
low-floor:
[0 1]
----------------------------------------
complimentary-tea:
[0 1]
----------------------------------------
coffee-tea-maker:
[0 1]
----------------------------------------
hot-spring-access:
[0 1]
----------------------------------------
bedroom_count:
[ 0  2  3  1 12  4  7 13  5 15  8  9  6 10 14 11 21 20 18]
----------------------------------------
price_option_price:
[289522. 361111. 601852. ... 220538. 270886. 273589.]
----------------------------------------
adults_number:
[ 2  4  1  3  6  5  8 10  7  9 12 16 11 40 25 30 50 45 13 14 15 20 26 24
 18 22 32  0 23 19]
----------------------------------------
children_number:
[ 0  2  1  4  6  3  5 10 12  8  9]
----------------------------------------
bãi_đậu_xe:
[1 0]
----------------------------------------
phòng_tập:
[0 1]
----------------------------------------
wifi_miễn_phí:
[1 0]
----------------------------------------
không_hoàn_tiền:
[0 1]
----------------------------------------
miễn_phí_hủy:
[1 0]
----------------------------------------
vào_hồ_bơi_miễn_phí:
[0 1]
----------------------------------------
đã_kèm_bữa_sáng:
[0 1]
----------------------------------------

Khi kiểm tra giá trị các trường ta nhận thấy trường sqm,price_option_price,adults_number,bathroom_count, flexibility_score,bedroom_count,children_number có biên độ giá trị khá cao, dễ ảnh hưởng đến kết quả khi train mô hình, ta cần chuẩn hoá về phân phối chuẩn (mean=0, variance =1)

In [5]:
cols_to_scale = [
    'sqm',
    'price_option_price',
    'adults_number',
    'bathroom_count',
    'flexibility_score',
    'bedroom_count',
    'children_number'
]

scaler = StandardScaler()

data2[cols_to_scale] = scaler.fit_transform(data2[cols_to_scale])

In [6]:
print(data2['sqm'].mean())      # ≈ 0
print(data2['sqm'].var())

3.305948255447458e-17
1.0000553924555475

Lưu kết quả của data đã tiền xử lý (optional)

In [7]:
#data2.to_csv('preprocess_final_totrain_rforest.csv')
#data2.head()

Xử lý trường hợp NaN của price_option_price

In [8]:
data2['price_option_price'] = data2['price_option_price'].fillna(data2['price_option_price'].median())
data2['sqm'] = data2['sqm'].fillna(data2['sqm'].median())

In [9]:
x_data = data2.drop(columns=['price_option_price'])
y_data = data2['price_option_price']
x_data

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,bedroom_count,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,-0.226625,...,-0.281742,0.870429,2.127743,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,4.232766,...,-0.281742,-0.269930,-0.646431,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19515,0,0,1,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
19516,0,0,1,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
19517,0,0,0,0,1,0,0,0,0,4.232766,...,-0.281742,0.870429,-0.646431,1,0,1,0,1,0,0
19518,1,0,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
19519,1,0,0,0,0,0,0,0,0,-0.226625,...,-0.281742,0.870429,-0.646431,1,0,1,0,1,0,0

In [10]:
y_data

0       -0.216136
1       -0.204025
2       -0.163296
3       -0.193059
4       -0.019804
           ...
19515   -0.227807
19516   -0.219289
19517   -0.218832
19518   -0.230825
19519   -0.217107
Name: price_option_price, Length: 19520, dtype: float64

Tách dữ liệu x,y ra thành 2 phần là x_train, y_train và x_test, y_test

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.25, random_state=42)

In [12]:
X_train.shape

(14640, 43)

In [13]:
X_test.shape

(4880, 43)

Tạo mô hình HistGradientBoostingRegressor để huấn luyện với tập luyện

In [14]:
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV

hist_gboost = HistGradientBoostingRegressor(loss='squared_error', random_state=42)

param_dist = {
    'learning_rate': np.linspace(0.03, 0.15, 10),
    'max_iter': [300, 600, 1000, 1600],
    'max_depth': [None, 6, 8, 10],
    'max_leaf_nodes': [15, 31, 63, 127],
    'min_samples_leaf': [20, 50, 100],
    'l2_regularization': np.logspace(-2, 1, 5)
}

hist_gboost_optim = RandomizedSearchCV(
    hist_gboost,
    param_distributions=param_dist,
    n_iter=40,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    random_state=42,
    verbose=2
)

hist_gboost_optim.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

RandomizedSearchCV(cv=5,
                   estimator=HistGradientBoostingRegressor(random_state=42),
                   n_iter=40, n_jobs=-1,
                   param_distributions={'l2_regularization': array([ 0.01      ,  0.05623413,  0.31622777,  1.77827941, 10.        ]),
                                        'learning_rate': array([0.03      , 0.04333333, 0.05666667, 0.07      , 0.08333333,
       0.09666667, 0.11      , 0.12333333, 0.13666667, 0.15      ]),
                                        'max_depth': [None, 6, 8, 10],
                                        'max_iter': [300, 600, 1000, 1600],
                                        'max_leaf_nodes': [15, 31, 63, 127],
                                        'min_samples_leaf': [20, 50, 100]},
                   random_state=42, scoring='neg_root_mean_squared_error',
                   verbose=2)

Đo lường điểm R2, MAE, MSE của mô hình

In [15]:
#R2 score
hist_gboost_optim.score(X_test, y_test)

-0.7732064493704627

In [16]:

y_pred = hist_gboost_optim.predict(X_test)
mean_squared_error(y_test, y_pred)
#MSE score

0.5978482133480779

In [17]:
#MAE score
mean_absolute_error(y_test, y_pred)

0.15579486433042264

In [18]:
#RMSE score
root_mean_squared_error(y_test, y_pred)

0.7732064493704627

Tạo mô hình AdaBoostRegressor

In [19]:
from sklearn.ensemble import AdaBoostRegressor
ada_gboost = AdaBoostRegressor()
param_dist_2 = {
    'n_estimators': np.arange(50, 500, 50),
    'learning_rate': np.linspace(0.01, 0.15, 10),
    'loss': ['linear', 'square', 'exponential'],
}

ada_gboost_optim = RandomizedSearchCV(
    ada_gboost,
    param_distributions=param_dist_2,
    n_iter=40,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    random_state=42,
    verbose=2
)
ada_gboost_optim.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

RandomizedSearchCV(cv=5, estimator=AdaBoostRegressor(), n_iter=40, n_jobs=-1,
                   param_distributions={'learning_rate': array([0.01      , 0.02555556, 0.04111111, 0.05666667, 0.07222222,
       0.08777778, 0.10333333, 0.11888889, 0.13444444, 0.15      ]),
                                        'loss': ['linear', 'square',
                                                 'exponential'],
                                        'n_estimators': array([ 50, 100, 150, 200, 250, 300, 350, 400, 450])},
                   random_state=42, scoring='neg_root_mean_squared_error',
                   verbose=2)

In [20]:
y_pred_ada = ada_gboost_optim.predict(X_test)
print(mean_squared_error(y_test, y_pred_ada)) #MSE
print(mean_absolute_error(y_test, y_pred_ada)) #MAE
print(ada_gboost_optim.score(X_test, y_test)) #R2
print(root_mean_squared_error(y_test, y_pred_ada))#RMSE score

1.5539299426684592
0.21776245632158792
-1.246567263595695
1.246567263595695

Tạo mô hình Decision Tree để đánh giá data

In [21]:
from sklearn.tree import DecisionTreeRegressor
decision_tree = DecisionTreeRegressor(criterion = 'squared_error', splitter='random')
decision_tree.fit(X_train, y_train)

DecisionTreeRegressor(splitter='random')

In [22]:
y_pred_decisiontree = decision_tree.predict(X_test)
print(decision_tree.score(X_test, y_test)) #R2 score 
print(mean_absolute_error(y_test,y_pred_decisiontree)) #MAE
print(mean_squared_error(y_test, y_pred_decisiontree))#MSE
print(root_mean_squared_error(y_test, y_pred_decisiontree))#RMSE score

0.1087066347876322
0.1357847468807058
0.6185905357753833
0.7865052674810152

Tạo mô hình Linear Regression để đánh giá data

In [23]:
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression(n_jobs = -1).fit(X_train, y_train)
y_pred_linearregression = linear_regression.predict(X_test)
print(linear_regression.score(X_test, y_test)) #R2 score 
print(mean_absolute_error(y_test,y_pred_linearregression)) #MAE
print(mean_squared_error(y_test, y_pred_linearregression))#MSE
print(root_mean_squared_error(y_test,y_pred_linearregression))#RMSE score

0.08731030448514177
0.2071616083987533
0.6334403797684337
0.7958896781391461