Cài đặt thư viện Scikit-learn để import model RandomForest

In [ ]:
!pip install -U scikit-learn

In [1]:
import numpy as np
import pandas as pd

Đọc data từ dữ liệu nhà nghỉ đã crawl

In [2]:
data = pd.read_csv("../Merge/final_selected_data.csv")
data.head()

,room_type_id,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,...,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng,hotel_id,room_room_type_name,hotel_name,hotel_address,region
0,1,1,0,0,0,0,0,0,0,0,...,1,0,1,0,0,71897952,Phòng Deluxe Có Giường Cỡ King (Deluxe King Room),Nha Nghi Nhung - Nhung Motel,"73 Đoàn Thị Điểm, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
1,2,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng Tiêu Chuẩn (Standard Room),Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
2,3,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng gia đình có ban công (Family Room with B...,Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
3,4,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,65481766,Phòng Có Giường Cỡ King Với Ban Công (King Roo...,Baly Hotel Bà Rịa City (Baly Hotel Ba Ria City),"QL51, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
4,5,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,5808626,Phòng Studio Executive (Studio Executive),Citadines Central Bình Dương (Citadines Centra...,"Số 328C, Đại lộ B nh Dương, Khu phố Hưng Lộc, ...",Bình Dương

Tạo một DataFrame mới tên là data2 từ data, ta bỏ 5 trường thuộc tính là hotel_id, hotel_name, room_room_type_name, hotel_name và hotel_address, views và regions

In [3]:
data2 = data.drop(columns=[
    'hotel_id',
    'hotel_name',
    'room_room_type_name',
    'hotel_address',
    'room_type_id', 
    'views', 'region'
])
data2.head()

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,price_option_price,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,289522.0,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,361111.0,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,601852.0,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,425926.0,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,1450000.0,2,0,0,0,1,0,0,0,0

Khi kiểm tra giá trị các trường ta nhận thấy trường sqm và price có biên độ giá trị khá cao, dễ ảnh hưởng đến kết quả khi train mô hình, ta cần chuẩn hoá về phân phối chuẩn (mean=0, variance =1)

In [4]:
data2['sqm']

0        18.0
1        30.0
2        45.0
3        20.0
4        35.0
         ...
19515    16.0
19516    16.0
19517    20.0
19518    15.0
19519    20.0
Name: sqm, Length: 19520, dtype: float64

In [5]:
data2['sqm'].isnull().any()

np.True_

In [6]:
data2['price_option_price'].isnull().any()

np.True_

Xử lý trường hợp NaN của sqm và price_option_price

In [7]:
data2['sqm'] = data2['sqm'].fillna(data2['sqm'].median())
data2['price_option_price'] = data2['price_option_price'].fillna(data2['price_option_price'].median())

Chuẩn hoá data2['sqm'] và data2['price_option_price']

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data2['sqm'] = scaler.fit_transform(data2[['sqm']])
data2['price_option_price'] = scaler.fit_transform(data2[['price_option_price']])

In [9]:
print(data2['sqm'].mean())      # ≈ 0
print(data2['sqm'].var())

1.7472362354756563e-17
1.000051232132794

In [10]:
data2.to_csv('preprocess_final_totrain_rforest.csv')
data2.head()

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,price_option_price,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,-0.216085,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,-0.203964,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,-0.163205,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,-0.192991,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,-0.019609,2,0,0,0,1,0,0,0,0

In [11]:
x_data = data2.drop(columns=['price_option_price'])
y_data = data2['price_option_price']
x_data

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,bedroom_count,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,0,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,0,2,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19515,0,0,1,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
19516,0,0,1,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
19517,0,0,0,0,1,0,0,0,0,2,...,0,4,0,1,0,1,0,1,0,0
19518,1,0,0,0,0,0,0,0,0,1,...,0,2,0,1,0,1,0,1,0,0
19519,1,0,0,0,0,0,0,0,0,1,...,0,4,0,1,0,1,0,1,0,0

In [12]:
y_data

0       -0.216085
1       -0.203964
2       -0.163205
3       -0.192991
4       -0.019609
           ...
19515   -0.227764
19516   -0.219240
19517   -0.218782
19518   -0.230784
19519   -0.217056
Name: price_option_price, Length: 19520, dtype: float64

Tách dữ liệu x,y ra thành 2 phần là x_train, y_train và x_test, y_test

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.25, random_state=42)

In [14]:
X_train.isnull().any()

large_double_bed                False
large_bed                       False
single_bed                      False
sofa_bed                        False
double_bed                      False
small_double_bed                False
king_size_bed                   False
futon_mattress                  False
bunk_bed                        False
flexibility_score               False
sqm                             False
bathroom_count                  False
is_private_bathroom             False
balcony-terrace                 False
closet                          False
air_conditioning                False
hair_dryer                      False
complimentary-bottled-water     False
bathtub                         False
shower                          False
refrigerator                    False
high-floor                      False
dressing-room                   False
ground-floor                    False
private-pool                    False
top-floor                       False
complimentary-instant-coffee    False
electric-blanket                False
free-welcome-drink              False
low-floor                       False
complimentary-tea               False
coffee-tea-maker                False
hot-spring-access               False
bedroom_count                   False
adults_number                   False
children_number                 False
bãi_đậu_xe                      False
phòng_tập                       False
wifi_miễn_phí                   False
không_hoàn_tiền                 False
miễn_phí_hủy                    False
vào_hồ_bơi_miễn_phí             False
đã_kèm_bữa_sáng                 False
dtype: bool

In [15]:
y_train.isnull().any()

np.False_

In [16]:
X_test.shape

(4880, 43)

In [17]:
y_test.shape

(4880,)

Đưa X_train và Y_train vào trong mô hình random forest regressor do trường Price là trường số có giá trị liên tục

In [22]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=43,
    n_jobs=2
)

rf_model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=43, n_jobs=2)

In [23]:
y_pred = rf_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2:", r2)

MSE: 1.148738615322444
R2: -0.6527444491410184

In [25]:
feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

print(feature_importance)

sqm                             0.185842
miễn_phí_hủy                    0.125979
bathroom_count                  0.101903
wifi_miễn_phí                   0.072804
private-pool                    0.064381
đã_kèm_bữa_sáng                 0.064016
large_bed                       0.061518
large_double_bed                0.034236
bãi_đậu_xe                      0.030941
is_private_bathroom             0.027344
adults_number                   0.024010
bedroom_count                   0.021055
ground-floor                    0.019978
phòng_tập                       0.017409
sofa_bed                        0.016209
bathtub                         0.013173
children_number                 0.013016
refrigerator                    0.011176
shower                          0.010347
dressing-room                   0.009637
air_conditioning                0.008846
double_bed                      0.007794
balcony-terrace                 0.007714
single_bed                      0.006155
không_hoàn_tiền                 0.006064
flexibility_score               0.004896
closet                          0.004892
hair_dryer                      0.004764
high-floor                      0.004713
top-floor                       0.003295
king_size_bed                   0.002683
vào_hồ_bơi_miễn_phí             0.002334
complimentary-instant-coffee    0.002246
low-floor                       0.001495
complimentary-bottled-water     0.001489
free-welcome-drink              0.001024
complimentary-tea               0.000986
bunk_bed                        0.000906
electric-blanket                0.000836
coffee-tea-maker                0.000757
futon_mattress                  0.000476
small_double_bed                0.000403
hot-spring-access               0.000257
dtype: float64