Cài đặt thư viện Scikit-learn để import model RandomForest

In [ ]:
!pip install -U scikit-learn

In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler

Đọc data từ dữ liệu nhà nghỉ đã crawl

In [3]:
data = pd.read_csv("../Merge/final_selected_data.csv")
data.head()

,room_type_id,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,...,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng,hotel_id,room_room_type_name,hotel_name,hotel_address,region
0,1,1,0,0,0,0,0,0,0,0,...,1,0,1,0,0,71897952,Phòng Deluxe Có Giường Cỡ King (Deluxe King Room),Nha Nghi Nhung - Nhung Motel,"73 Đoàn Thị Điểm, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
1,2,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng Tiêu Chuẩn (Standard Room),Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
2,3,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,49685029,Phòng gia đình có ban công (Family Room with B...,Nhà nghỉ Ruby Bà Rịa (Ruby Motel Bà Rịa),"KDC Baria City Gate, Long Huong Ward, Ba Ria C...",Bà Rịa
3,4,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,65481766,Phòng Có Giường Cỡ King Với Ban Công (King Roo...,Baly Hotel Bà Rịa City (Baly Hotel Ba Ria City),"QL51, Bà Rịa, Bà Rịa, Việt Nam",Bà Rịa
4,5,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,5808626,Phòng Studio Executive (Studio Executive),Citadines Central Bình Dương (Citadines Centra...,"Số 328C, Đại lộ B nh Dương, Khu phố Hưng Lộc, ...",Bình Dương

Tạo một DataFrame mới tên là data2 từ data, ta bỏ 5 trường thuộc tính là hotel_id, hotel_name, room_room_type_name, hotel_name và hotel_address, views và regions

In [4]:
data2 = data.drop(columns=[
    'hotel_id',
    'hotel_name',
    'room_room_type_name',
    'hotel_address',
    'room_type_id', 
    'views', 'region'
])
data2.head()

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,price_option_price,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,1,...,289522.0,2,0,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,1,...,361111.0,2,0,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,601852.0,4,2,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,1,...,425926.0,2,0,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,2,...,1450000.0,2,0,0,0,1,0,0,0,0

Khi kiểm tra giá trị các trường ta nhận thấy trường sqm,price_option_price,adults_number,bathroom_count, flexibility_score,bedroom_count,children_number có biên độ giá trị khá cao, dễ ảnh hưởng đến kết quả khi train mô hình, ta cần chuẩn hoá về phân phối chuẩn (mean=0, variance =1)

In [5]:
data2['sqm'] = data2['sqm'].fillna(data2['sqm'].median())
data2['price_option_price'] = data2['price_option_price'].fillna(data2['price_option_price'].median())

Chuẩn hoá data2['sqm'] và data2['price_option_price']

In [6]:
cols_to_scale = [
    'sqm',
    'price_option_price',
    'adults_number',
    'bathroom_count',
    'flexibility_score',
    'bedroom_count',
    'children_number'
]

scaler = StandardScaler()

data2[cols_to_scale] = scaler.fit_transform(data2[cols_to_scale])

In [7]:
print(data2['sqm'].mean())      # ≈ 0
print(data2['sqm'].var())

1.7472362354756563e-17
1.000051232132794

In [8]:
#data2.to_csv('preprocess_final_totrain_rforest.csv')
#data2.head()

In [9]:
x_data = data2.drop(columns=['price_option_price'])
y_data = data2['price_option_price']
x_data

,large_double_bed,large_bed,single_bed,sofa_bed,double_bed,small_double_bed,king_size_bed,futon_mattress,bunk_bed,flexibility_score,...,bedroom_count,adults_number,children_number,bãi_đậu_xe,phòng_tập,wifi_miễn_phí,không_hoàn_tiền,miễn_phí_hủy,vào_hồ_bơi_miễn_phí,đã_kèm_bữa_sáng
0,1,0,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
1,0,1,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
2,0,1,0,0,0,0,0,0,0,-0.226625,...,-0.281742,0.870429,2.127743,1,0,1,0,1,0,0
3,0,1,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,4.232766,...,-0.281742,-0.269930,-0.646431,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19515,0,0,1,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
19516,0,0,1,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
19517,0,0,0,0,1,0,0,0,0,4.232766,...,-0.281742,0.870429,-0.646431,1,0,1,0,1,0,0
19518,1,0,0,0,0,0,0,0,0,-0.226625,...,-0.281742,-0.269930,-0.646431,1,0,1,0,1,0,0
19519,1,0,0,0,0,0,0,0,0,-0.226625,...,-0.281742,0.870429,-0.646431,1,0,1,0,1,0,0

In [10]:
y_data

0       -0.216085
1       -0.203964
2       -0.163205
3       -0.192991
4       -0.019609
           ...
19515   -0.227764
19516   -0.219240
19517   -0.218782
19518   -0.230784
19519   -0.217056
Name: price_option_price, Length: 19520, dtype: float64

Tách dữ liệu x,y ra thành 2 phần là x_train, y_train và x_test, y_test

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.25, random_state=42)

In [12]:
X_train.isnull().any()

large_double_bed                False
large_bed                       False
single_bed                      False
sofa_bed                        False
double_bed                      False
small_double_bed                False
king_size_bed                   False
futon_mattress                  False
bunk_bed                        False
flexibility_score               False
sqm                             False
bathroom_count                  False
is_private_bathroom             False
balcony-terrace                 False
closet                          False
air_conditioning                False
hair_dryer                      False
complimentary-bottled-water     False
bathtub                         False
shower                          False
refrigerator                    False
high-floor                      False
dressing-room                   False
ground-floor                    False
private-pool                    False
top-floor                       False
complimentary-instant-coffee    False
electric-blanket                False
free-welcome-drink              False
low-floor                       False
complimentary-tea               False
coffee-tea-maker                False
hot-spring-access               False
bedroom_count                   False
adults_number                   False
children_number                 False
bãi_đậu_xe                      False
phòng_tập                       False
wifi_miễn_phí                   False
không_hoàn_tiền                 False
miễn_phí_hủy                    False
vào_hồ_bơi_miễn_phí             False
đã_kèm_bữa_sáng                 False
dtype: bool

In [13]:
y_train.isnull().any()

np.False_

In [14]:
X_test.shape

(4880, 43)

In [15]:
y_test.shape

(4880,)

Đưa X_train và Y_train vào trong mô hình random forest regressor do trường Price là trường số có giá trị liên tục

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_dist = {
    'n_estimators': np.arange(200, 600, 50),
    'max_depth': [None, 10, 15, 20, 30],
    'min_samples_leaf': [5, 10, 20, 50],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 0.3, 0.5, 0.7]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=30,
    scoring='neg_root_mean_squared_error',
    cv=3,
    n_jobs=-1,
    random_state=42,
    verbose=2
)

random_search.fit(X_train, y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

RandomizedSearchCV(cv=3,
                   estimator=RandomForestRegressor(n_jobs=-1, random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'max_depth': [None, 10, 15, 20, 30],
                                        'max_features': ['sqrt', 0.3, 0.5, 0.7],
                                        'min_samples_leaf': [5, 10, 20, 50],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': array([200, 250, 300, 350, 400, 450, 500, 550])},
                   random_state=42, scoring='neg_root_mean_squared_error',
                   verbose=2)

In [17]:
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error 

y_pred = random_search.predict(X_test)
print(mean_squared_error(y_test, y_pred)) #MSE
print(mean_absolute_error(y_test, y_pred)) #MAE
print(random_search.score(X_test, y_test)) #R2
print(root_mean_squared_error(y_test, y_pred))#RMSE score

0.5915476398254104
0.14848571225519636
-0.7691213427186964
0.7691213427186964